//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SazBaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackSlider
    {
        public int Id { get; set; }
        public string back_slider_img { get; set; }
    }
}
