//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SazBaki.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SazBakiEntities : DbContext
    {
        public SazBakiEntities()
            : base("name=SazBakiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackSlider> BackSliders { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<HomeContent> HomeContents { get; set; }
        public virtual DbSet<MultipeSlider> MultipeSliders { get; set; }
        public virtual DbSet<OrderTable> OrderTables { get; set; }
        public virtual DbSet<Admintb> Admintbs { get; set; }
        public virtual DbSet<Navbar> Navbars { get; set; }
    }
}
